# Date of creation: 20230804 UNIX Time :1691161692.1725187
# File GDML : LEM_Ibrido_modificaCono-tessellated-worldVOL_Parsed_DummyMaterials.gdml


/control/verbose 0
/run/verbose 1
/event/verbose 0


/run/initialize


/random/setSeeds 4 4


/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 0 12 cm
/gps/pos/radius 0.5 cm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 5 deg



/NameOfFile/NameOfFile /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230804_test/DST/GDML_file_1/e-_j4
/gps/particle e-
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 0.08 MeV
/gps/ene/max 20 MeV
/run/beamOn 100000
/NameOfFile/NameOfFile /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230804_test/DST/GDML_file_1/proton_j4
/gps/particle proton
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 2 MeV
/gps/ene/max 100 MeV
/run/beamOn 100000
/NameOfFile/NameOfFile /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230804_test/DST/GDML_file_1/alpha_j4
/gps/particle alpha
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 10 MeV
/gps/ene/max 500 MeV
/run/beamOn 100000
