# Date of creation: 20230617 UNIX Time :<built-in function time>
/control/verbose 0
/gps/position 0 0 13 cm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 5 deg
/gps/direction 0 0 -1
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_PID_20230617/DST/GDML_file_0/e-
/gps/particle e-
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 0.08 MeV
/gps/ene/max 30 MeV
/run/beamOn 2000000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_PID_20230617/DST/GDML_file_0/proton
/gps/particle proton
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 1 MeV
/gps/ene/max 300 MeV
/run/beamOn 2000000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_PID_20230617/DST/GDML_file_0/alpha
/gps/particle alpha
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 10 MeV
/gps/ene/max 800 MeV
/run/beamOn 2000000
