# Date of creation: 20230712 UNIX Time :<built-in function time>
# File GDML : LEM_Ibrido_modificaCono-tessellated-worldVOL_Parsed.gdml
/RunAction/OutputTextFolder /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230712/Text_output/GDML_file_2
/EventAction/OutputTextFolder /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230712/Text_output/GDML_file_2
/DetectorConstruction/OutputTextFolder /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230712/Text_output/GDML_file_2



/run/initialize
/control/verbose 0
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 0 12 cm
/gps/pos/radius 3.0 cm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230712/DST/GDML_file_2/e-
/gps/particle e-
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 0.08 MeV
/gps/ene/max 20 MeV
/run/beamOn 1000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230712/DST/GDML_file_2/proton
/gps/particle proton
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 2 MeV
/gps/ene/max 100 MeV
/run/beamOn 1000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230712/DST/GDML_file_2/alpha
/gps/particle alpha
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 10 MeV
/gps/ene/max 500 MeV
/run/beamOn 1000
