universe = vanilla
getenv = True
stream_output = True
stream_error = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/bash_scripts/launch_f0_j55.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/log/out_f0_j55.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/log/err_f0_j55.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/log/log_f0_j55.log
priority = 5
queue 1
