universe = vanilla
getenv = True
stream_output = True
stream_error = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/bash_scripts/launch_f5_j53.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/log/out_f5_j53.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/log/err_f5_j53.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230814/log/log_f5_j53.log
priority = 5
queue 1
