universe = vanilla
getenv = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/bash_scripts/launch_f1_j6.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/out_f1_j6.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/err_f1_j6.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/log_f1_j6.log
queue 1
