universe = vanilla
getenv = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/bash_scripts/launch_f3_j1.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/out_f3_j1.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/err_f3_j1.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/log_f3_j1.log
queue 1
