universe = vanilla
getenv = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/bash_scripts/launch_f2_j9.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/out_f2_j9.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/err_f2_j9.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230717/log/log_f2_j9.log
queue 1
