# Date of creation: 20230607 UNIX Time :<built-in function time>
/control/verbose 0
/gps/pos/type Point
/gps/pos/shape Circle
/gps/position 0 0 11 cm
/gps/pos/radius 40 cm
/gps/ang/type beam1d
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg
/gps/direction 0 0 -1
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230607/DST/GDML_file_0/e-
/gps/particle e-
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 0.08 MeV
/gps/ene/max 20 MeV
/run/beamOn 10000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230607/DST/GDML_file_0/proton
/gps/particle proton
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 2 MeV
/gps/ene/max 100 MeV
/run/beamOn 10000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230607/DST/GDML_file_0/alpha
/gps/particle alpha
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 20 MeV
/gps/ene/max 500 MeV
/run/beamOn 10000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230607/DST/GDML_file_0/gamma
/gps/particle gamma
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 0.01 MeV
/gps/ene/max 10 MeV
/run/beamOn 10000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230607/DST/GDML_file_0/mu-
/gps/particle mu-
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 10000.0 MeV
/gps/ene/max 100000.0 MeV
/run/beamOn 10000
