# Date of creation: 20230615 UNIX Time :<built-in function time>
# File GDML : LEM_Ibrido_modificaCono-tessellated-worldVOL_Parsed.gdml
/control/verbose 0
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 0 11.24 cm
/gps/pos/radius 1.3 cm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230615/DST/GDML_file_0/e-
/gps/particle e-
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 0.08 MeV
/gps/ene/max 20 MeV
/run/beamOn 5000000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230615/DST/GDML_file_0/proton
/gps/particle proton
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 2 MeV
/gps/ene/max 100 MeV
/run/beamOn 5000000
/NameOfFile/NameOfFile /home/riccardo/Documenti/GeantProjects/LEM_GDML_upgrade/Output_Geant4Simulation_20230615/DST/GDML_file_0/alpha
/gps/particle alpha
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ene/min 20 MeV
/gps/ene/max 500 MeV
/run/beamOn 5000000
