universe = vanilla
getenv = True
stream_output = True
stream_error = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/bash_scripts/launch_f4_j0.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/log/out_f4_j0.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/log/err_f4_j0.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/log/log_f4_j0.log
priority = 5
queue 1
