universe = vanilla
getenv = True
stream_output = True
stream_error = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/bash_scripts/monitoring.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/log/out_monitoring.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/log/err_monitoring.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230817_test/log/log_monitoring.log
priority = 10
queue 1
