universe = vanilla
getenv = True

stream_output = True
stream_error = True

output = /data1/home/rnicolai/LEM_GDML_upgrade/PythonMacros/Condor_utils/out.txt
error = /data1/home/rnicolai/LEM_GDML_upgrade/PythonMacros/Condor_utils/err.txt
log = /data1/home/rnicolai/LEM_GDML_upgrade/PythonMacros/Condor_utils/log.txt




executable = /data1/home/rnicolai/LEM_GDML_upgrade/PythonMacros/Condor_utils/job_submission.sh



queue 