universe = vanilla
getenv = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/bash_scripts/launch_f2_j3.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/log/out_f2_j3.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/log/err_f2_j3.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/log/log_f2_j3.log
queue 1
