universe = vanilla
getenv = True
executable = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/bash_scripts/launch_f0_j4.sh
output = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/log/out_f0_j4.log
error = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/log/err_f0_j4.log
log = /data1/home/rnicolai/LEM_GDML_upgrade/Output_Geant4Simulation_20230802/log/log_f0_j4.log
queue 1
